# /////////////////////////////////////////////////////////////
# /                                                           /
# /                      Logger Plugin                        /
# /                                                           /
# /                    [ Bukkit Version ]                     /
# /                                                           /
# /////////////////////////////////////////////////////////////
# Thank you for using Logger Plugin! If you are experiencing any issues
# or have any suggestions / features you want to be implemented into the plugin
# feel free to join the support Discord Server!
# Spigot: Prism3
# Discord: Prism3#9371 ID: 403667971089760257
# Discord Server: https://discord.gg/MfR5mcpVfX
# Config: 1.8
Language: en_en
Server-Name: "Server_Name"
Plugin-Prefix: "&bLogger &8&l| &r "
Time-Formatter: "yyyy-MM-dd HH:mm:ss"
File-Deletion: 7
Log-to-Files: true
Staff:
  Enabled: false
Log-Player:
  Chat: true
  Commands: true
  Sign-Text: true
  Join: true
  Leave: true
  Kick: true
  Death: true
  Teleport: true
  Level: true
  Block-Place: true
  Block-Break: true
  Bucket-Fill: true
  Bucket-Empty: true
  Anvil: true
  Item-Pickup: true
  Item-Drop: true
  Enchanting: true
  Book-Editing: true
  Furnace: true
  Game-Mode: true
  Craft: true
  Registration: true
  Primed-TNT: true
  Chest-Interaction: true
  Entity-Death: true
Log-Server:
  Start: true
  Stop: true
  Console-Commands: true
  RAM: true
  TPS: true
  Portal-Creation: true
  RCON: true
  Command-Block: true
Log-Extras:
  Essentials-AFK: true
  AuthMe-Wrong-Password: true
  Vault: true
  LiteBans: true
  AdvancedBan: true
Log-Version-Exceptions:
  Wood-Stripping: true
Player-Commands:
  Whitelist-Commands: false
  Commands-to-Log:
    - /msg
    - /sell
    - /plugins
    - /pl
    - /about
  Blacklist-Commands: true
  Commands-to-Block:
    - /login
    - /changepassword
    - /register
Player-Join:
  Player-IP: false
Player-Level:
  Log-Above: 100
Game-Mode: Creative
Player-Death-Backup:
  Enabled: true
  Max-Backup: 7
Console-Commands:
  Blacklist-Commands: false
  Commands-to-Block:
    - list
    - op
    - ban
RAM-TPS-Checker: 6000
Vault-Checker: 6000
RAM:
  Percent: 50
TPS:
  Value-Medium: 16
  Value-Critical: 7
Spy-Features:
  Commands-Spy:
    Enable: false
    Message: "&8[&bLogger &8&l| &eCommand-Spy&8] &7%player% >> %cmd%"
  Book-Spy:
    Enable: false
    Message: "&8[&bLogger &8&l| &eBook-Spy&8] &7%player% >> %content%"
  Sign-Spy:
    Enable: false
    Message: "&8[&bLogger &8&l| &eSign-Spy&8] &7%player% >> %line1%, %line2%, %line3%, %line4%"
  Anvil-Spy:
    Enable: false
    Message: "&8[&bLogger &8&l| &eAnvil-Spy&8] &7%player% >> %renamed%"
Database:
  Enable: false
  Type: MySQL
  Host: localhost
  Port: 3306
  Username: username
  Password: PassworD
  Database: database
  Data-Deletion: 7
SQLite:
  Enable: false
  Data-Deletion: 7
Update-Checker: true