# /////////////////////////////////////////////////////////////
# /                                                           /
# /                      Logger Plugin                        /
# /                                                           /
# /////////////////////////////////////////////////////////////
#
# Thank you for using Logger Plugin! If you are experiencing any issues
# or have any suggestions / features you want to be implemented into the plugin
# feel free to join the support Discord Server!
#
# Spigot: Prism3
# Discord: Prism3#5787 | ID: 403667971089760257
# Discord Server: https://discord.gg/MfR5mcpVfX

# Server Name
Server-Name: "Server_Name"

# How many Days for the logs to be deleted
# Set it to -1 to cancel the Deletion
File-Deletion: 7

# Log to Files
Log-to-Files: true

# This will log players with "logger.staff.log" permission node in their own folder / file
Staff:
  Enabled: false

# Logging features
# AFK Feature depends on Essentials Plugin
Log:
  Player-Chat: true
  Player-Commands: true
  Console-Commands: true
  Player-Sign-Text: true
  Player-Join: true
  Player-Leave: true
  Player-Kick: true
  Player-Death: true
  Player-Teleport: true
  Player-Level: true
  Block-Place: true
  Block-Break: true
  Portal-Creation: true
  Bucket-Place: true
  Anvil: true
  TPS: true
  RAM: true
  Server-Start: true
  Server-Stop: true
  Item-Pickup: true
  Item-Drop: true
  Enchanting: true
  Book-Editing: true
  AFK: true
  Furnace: true

# How often should we check for the Server's TPS and RAM
# It's better to have it above 1 min to avoid any complications
# Value in Ticks, 20 Ticks = 1 Second
RAM-TPS-Checker: 6000

# Server TPS Logging
TPS:
  Value-Medium: 16
  Value-Critical: 7

# Server RAM Log
# Percent goes from 0 -> 100
RAM:
  Percent: 50

# Log players if their level exceeds the set amount
Player-Level:
  Log-Above: 100

# Only Log Specified Commands
# Block Commands from getting Logged
Player-Commands:
  Whitelist-Commands: false
  Commands-to-Log:
    - /msg
    - /sell
    - /plugins
    - /pl
    - /about
  Blacklist-Commands: true
  Commands-to-Block:
    - /login
    - /changepassword
    - /register
  Commands-Spy:
    Enable: false
    Message: "&8[&6Spy&8] &7%player% >> %cmd%"

# Disable this if you want to hide Player's IPs
Player-Join:
  Player-IP: true

# Items to be picked up
Item-Pickup:
  - "APPLE"
  - "BARRIER"
  - "BEDROCK"

# MySQL Feature
# Data-Deletion Value in Days, Set it -1 to cancel
MySQL:
  Enable: false
  Host: localhost
  Port: 3306
  Username: username
  Password: PassworD
  Database: database
  Data-Deletion: 7

# SQLite Feature
# Data-Deletion Value in Days, Set it -1 to cancel
SQLite:
  Enable: false
  Data-Deletion: 7

Messages:
  No-Permission: "&cYou do not have permission to run this command."
  Reload-Message: "&aConfigs Reloaded."